{% set name = "literalai" %}
{% set version = "0.1.201" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/literalai-{{ version }}.tar.gz
  sha256: 29e4ccadd9d68bfea319a7f0b4fc32611b081990d9195f98e5e97a14d24d3713

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - packaging >=23.0
    - httpx >=0.23.0
    - pydantic >=1,<3
    - chevron >=0.14.0
    - traceloop-sdk >=0.33.12

test:
  imports:
    - literalai
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.literalai.com
  doc_url: https://docs.getliteral.ai
  dev_url: https://github.com/Chainlit/literalai-python
  summary: An SDK for observability in Python applications
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
